### PR TITLE
Make extension work on the latest iOS (18)

### PR DESCRIPTION
**Pull request by fishcakeday**
- Update all dependencies
- Prettier the code
- Make it work on iOS18

### CODE REVIEW

**Comment by Sjors** [comment]
Hopefully this fixes macOS Safari too?

**Comment by editwentyone** [comment]
it does

**Comment by Sjors** [comment]
Don't forgot to release it there? Or are you still waiting for the Apple overloards to approve? See #22.

**Comment by joshuatbrown** [comment]
Is there somewhere I can download Nostore for macOS 14.7.2 with this fix? I'm seeing a screen like what's in #20 and can't update to the latest from the App Store since I'm still on macOS 14.7.2. Or maybe what I'm requesting is that the App Store version still support macOS 14.x?

Screenshot 2025-01-03 at 5 36 38 PM

**Pull request merged**
